# BneHomes Konfiguration
database:
  type: "sqlite" # "mysql" oder "sqlite"
  host: "localhost"
  port: 3306
  name: "minecraft"
  user: "root"
  password: ""

settings:
  max_homes: 5
  teleport_delay: 3 # Sekunden (optional für später)